#!/bin/bash

jardir="$(cd "$(dirname "$0")" && pwd -P)"

java=java

if [ -e "$JAVA_HOME/bin/java" ]
then
	java="$JAVA_HOME/bin/java"
fi

default_jvm_mem_opts="-Xms1g -Xmx8g"
jvm_mem_opts=""
jvm_prop_opts=""
pass_args=""
for arg in "$@"; do
    case $arg in
        '-D'*)
            jvm_prop_opts="$jvm_prop_opts $arg"
            ;;
         '-Xm'*)
            jvm_mem_opts="$jvm_mem_opts $arg"
            ;;
         *)
            pass_args="$pass_args $arg"
            ;;
    esac
done

if [ "$jvm_mem_opts" == "" ]; then
    jvm_mem_opts="$default_jvm_mem_opts"
fi

exec $java $jvm_mem_opts $jvm_prop_opts -jar ${jardir}/picard.jar $pass_args
exit
